# Generated by Django 5.0.7 on 2024-08-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_likes',
            new_name='user_like',
        ),
    ]
